### PR TITLE
Added bootstrap-table-export extension to export table data in Sampuru

### PR DESCRIPTION
**Pull request by isamohideen**

### CODE REVIEW

**Comment by avarsava** [comment]
When building the project, I get two warnings:
`
sampuru-ui/src/project.ts:4:23 - error TS2688: Cannot find type definition file for 'file-saver'.

4 /// <reference types="file-saver" />
                        ~~~~~~~~~~

sampuru-ui/src/qcables.ts:4:23 - error TS2688: Cannot find type definition file for 'file-saver'.

4 /// <reference types="file-saver" />
                        ~~~~~~~~~~
`

**Comment by avarsava** [comment]
I built off develop and can load the project info page just fine, but with this branch checked out the project info page has the javascript error:
`Uncaught TypeError: Error resolving module specifier “d3”. Relative module specifiers must start with “./”, “../” or “/”.` on `sankey.js:3:20`

**Comment by avarsava** [comment]
Putting a button to the right of a search box will make it look like it's a search button. I'd recommend rearranging these elements 
image

**Comment by avarsava** [comment]
Please update the User Manual to explain this feature, especially what the distinction between 'Export Basic', 'Export All', and 'Export Selected' is. I can't figure out how to 'Select' one or more rows.

**Comment by avarsava** [comment]
I tried 'Export Selected' on this particular table, and the TXT file I got back seems to have a problem:
image
Receipt/Inspection has the case name repeated twice.

**Comment by avarsava** [comment]
When exporting 'Basic', if a 'Not started yet' cell has been clicked, the string "not started yet" gets exported, otherwise the cell is blank. This might trip up a script consuming the output

**Comment by avarsava** [comment]
The QC-ables page for ABMT has 141 rows, of which 10 are shown by default. 'Export All' only exports the 10 shown, meaning if the user wanted to export all 141, they'd have to (at least) set the page to show 100 rows, export both pages, then concatenate them together.

**Comment by isamohideen** [comment]
@avarsava with regards to your first two comments, this may be because I added some dependencies to package.json. Did you run `npm install` before building the project?

**Comment by isamohideen** [comment]
> 

I'm not sure if it needs to be run every time the project is built, to my understanding it's just used when there are new dependencies added to `package.json`

**Comment by avarsava** [comment]
That seems to have fixed the d3 issue and cleared the errors, thanks!

**Review by asofmosq — APPROVED** [review]

**Review by avarsava — APPROVED** [review]

**Pull request merged**
