### PR TITLE
[GP-4404] Security updates

### PR DESCRIPTION
**Pull request by wuall826**
Security updates and typescript error fix

### CODE REVIEW

**Comment by avarsava** [comment]
Trying to rebuild the frontend results in 
```
[!] (plugin node-resolve) Error: Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.61.1.
```
for me?

**Comment by wuall826** [comment]
> Trying to rebuild the frontend results in
> 
> ```
> [!] (plugin node-resolve) Error: Insufficient rollup version: "@rollup/plugin-node-resolve" requires at least rollup@2.78.0 but found rollup@2.61.1.
> ```
> 
> for me?

hmm that's really odd, roll up is at "rollup": "^4.22.4" now in package.json, it's at "rollup": "^2.36.1" on the develop branch though. Maybe because of local setup?

**Comment by avarsava** [comment]
Opened https://github.com/oicr-gsi/sampuru/pull/141 about above issue

**Review by avarsava — APPROVED** [review]

**Comment by grapigeau** [comment]
You'll need to change the readme to reflect the needed node version:
```
npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@4.22.4',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.7.6' }
npm WARN EBADENGINE }

```

**Review by grapigeau — APPROVED** [review]

**Pull request merged**
