### PR TITLE
[GR-1326] Show number of cases at each QC gate

### PR DESCRIPTION
**Pull request by asofmosq**

### CODE REVIEW

**Review by avarsava — COMMENTED** [review]
Table looks good, but visually it's inconsistent with the rest of sampuru - everywhere we chart out qcable progress, receipt -> final report is represented horizontally left to right, could the table be pivoted if not switched to reusing the display from the Cases card?

**Comment by avarsava** [comment]
Also, the section of the Project Info page is "Number of Cases Per QC Gate" but the table column is "# of _Completed_ Cases", is the intention to also add an Incomplete Cases column or should the naming be brought into sync?

**Review by djcooke — APPROVED** [review]

**Comment by avarsava** [comment]
Could we fix the width of the table to the width of the card and make the header cells take up 2 lines rather than have this tiny overflow?
image

**Comment by asofmosq** [comment]
@avarsava I can make the font size 1px smaller which will remove the overflow when a browser window is full-size but I think it would make the table more confusing to read if the header cells span two lines. If the window is smaller than full-size, it makes sense to have horizontal scroll but it would become increasingly unreadable as a window shrinks if the header spans two lines.

**Review by avarsava — APPROVED** [review]

**Pull request merged**
